-- Run this in the Supabase SQL Editor (Project -> SQL Editor -> New query)
-- to create the tables the app expects.

create table if not exists public.weights (
    id bigint generated by default as identity primary key,
    name text not null,
    date text not null,           -- stored as mm-dd-yyyy text, same as the old SQLite app
    weight double precision not null,
    created_at timestamptz not null default now()
);

create table if not exists public.workouts (
    id bigint generated by default as identity primary key,
    name text not null,
    date text not null,           -- stored as mm-dd-yyyy text, same as the old SQLite app
    lift_split text not null,
    secondary_muscle_group text,
    cardio_done boolean not null,
    cardio_type text,
    cardio_distance_miles double precision,
    cardio_duration_minutes integer,
    created_at timestamptz not null default now()
);

-- Helpful for the "ORDER BY date" queries the app makes.
create index if not exists weights_date_idx on public.weights (date);
create index if not exists workouts_date_idx on public.workouts (date, id);

-- This is a single-user app talking to Supabase with the service role key
-- from a trusted backend, so RLS is left disabled. If you ever expose these
-- tables to a browser-side Supabase client (anon key), enable RLS and add
-- policies before doing so:
--   alter table public.weights enable row level security;
--   alter table public.workouts enable row level security;
